### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by DaErkiman** [sle118/hayward_pool_heater#3]
Thank you for this project!

I am getting compile error when trying to write the project to a ESP32 device, I have tried several different units.

Compilation log:

```
INFO ESPHome 2025.3.3
INFO Reading configuration /config/esphome/esp-pool-heater.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp-pool-heater (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.3.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/esp-pool-heater/src/main.cpp.o
Building .pioenvs/esp-pool-heater/bootloader.bin
Generating partitions .pioenvs/esp-pool-heater/partitions.bin
Creating esp32 image...
Successfully created esp32 image.
Compiling .pioenvs/esp-pool-heater/libe6d/AsyncTCP-esphome/AsyncTCP.cpp.o
In file included from src/esphome/components/hwp/Bus.h:45,
                 from src/esphome.h:29,
                 from src/main.cpp:3:
src/esphome/components/hwp/Schema.h:455:52: error: macro "bit" passed 2 arguments, but takes just 1
     static std::string bit(uint8_t raw, uint8_t ref) {
                                                    ^
In file included from src/esphome.h:42,
                 from src/main.cpp:3:
src/esphome/components/hwp/FrameConf5.h:86:74: error: macro "bit" passed 2 arguments, but takes just 1
         oss << "( " << bits_details::bit(this->unknown_1, other.unknown_1)
                                                                          ^
src/esphome/components/hwp/FrameConf5.h:87:66: error: macro "bit" passed 2 arguments, but takes just 1
             << bits_details::bit(this->unknown_2, other.unknown_2) << "[U01 Flow meter: "
                                                                  ^
src/esphome/components/hwp/FrameConf5.h:89:66: error: macro "bit" passed 2 arguments, but takes just 1
             << bits_details::bit(this->unknown_4, other.unknown_4)
                                                                  ^
src/esphome/components/hwp/FrameConf5.h:90:66: error: macro "bit" passed 2 arguments, but takes just 1
             << bits_details::bit(this->unknown_5, other.unknown_5)
                                                                  ^
src/esphome/components/hwp/FrameConf5.h:91:66: error: macro "bit" passed 2 arguments, but takes just 1
             << bits_details::bit(this->unknown_6, other.unknown_6) << " [d06 defrost: "
                                                                  ^
src/esphome/components/hwp/FrameConf5.h:93:66: error: macro "bit" passed 2 arguments, but takes just 1
             << bits_details::bit(this->unknown_8, other.unknown_8) << " )" << sep;
                                                                  ^
In file included from src/esphome.h:53,
                 from src/main.cpp:3:
src/esphome/components/hwp/switch_helpers.h:36:10: fatal error: esphome/components/switch/switch.h: No such file or directory
 #include "esphome/components/switch/switch.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/esp-pool-heater/lib64d/WiFi/WiFi.cpp.o
*** [.pioenvs/esp-pool-heater/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.81 seconds ==========================

```

Here is my .yaml file:

```
esphome:
  name: esp-pool-heater
  friendly_name: ESP Pool Heater

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxx"

ota:
  - platform: esphome
    password: "xxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Pool-Heater Fallback Hotspot"
    password: "xxxxxx"

captive_portal:

external_components:
  - source: github://sle118/hayward_pool_heater
    components: hwp

climate:
  - platform: hwp
    id: pool_heater
    name: "Pool Heater"
    pin_txrx: GPIO22 
```

Does anyone have an idea on what the problem is?

**Comment by sle118** [comment]
Try to use the ESP-IDF framework. 

```
esp32:
  # board: lolin_s2_mini
  board: esp32dev
  framework:
    type: esp-idf
```

I have not tried to compile with the arduino framework, but there could be some issue if I used some esp-idf calls. I can't remember right now.

**Comment by njanik** [comment]
Hello! I will soon be able to be a beta tester, the preparation of the pool is coming :wink:

**Comment by ricko07** [comment]
I have a compilation error, I tried
```
esp32:
  # board: lolin_s2_mini
  board: esp32dev
  framework:
    type: esp-idf

``` 

```
INFO ESPHome 2025.4.2
INFO Reading configuration /config/esphome/pool-heater.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing pool-heater (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/pool-heater/src/main.cpp.o
Compiling .pioenvs/pool-heater/app_update/esp_ota_app_desc.c.o
Archiving .pioenvs/pool-heater/esp-idf/app_update/libapp_update.a
Compiling .pioenvs/pool-heater/bootloader_support/src/bootloader_common.c.o
Compiling .pioenvs/pool-heater/bootloader_support/src/bootloader_common_loader.c.o
In file included from src/esphome/components/hwp/base_frame.h:44,
                 from src/esphome/components/hwp/Bus.h:46,
                 from src/esphome.h:29,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-espidf/components/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
In file included from src/esphome.h:53:
src/esphome/components/hwp/switch_helpers.h:36:10: fatal error: esphome/components/switch/switch.h: No such file or directory
   36 | #include "esphome/components/switch/switch.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/pool-heater/src/main.cpp.o] Error 1
========================== [FAILED] Took 5.31 seconds ==========================
``` 

Configuration:

```
esphome:
  name: pool-heater
  friendly_name: Pool_Heater

esp32:
  # board: lolin_s2_mini
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "******************************"

ota:
  - platform: esphome
    password: "**********************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pool-Heater Fallback Hotspot"
    password: "**************"

captive_portal:

external_components:
  - source: github://sle118/hayward_pool_heater
    components: hwp

climate:
  - platform: hwp
    id: pool_heater
    name: "Pool Heater"
    pin_txrx: GPIO22 
```
